### ISSUE TITLE
Expected only three 'NPDE' markers

### ISSUE THREAD

**Issue by svenmauch** [Matoking/NVIDIA-vBIOS-VFIO-Patcher#7]
Getting this output:

```
[mauch@M80 NVIDIA-vBIOS-VFIO-Patcher]$ python nvidia_vbios_vfio_patcher.py -i mx150.rom -o mx150patched.rom
Opening the ROM file...
Scanning for ROM offsets...
Offsets found!
Running sanity checks...
Traceback (most recent call last):
File "nvidia_vbios_vfio_patcher.py", line 194, in <module>
main()
File "nvidia_vbios_vfio_patcher.py", line 172, in main
rom.run_sanity_tests(args.ignore_sanity_check)
File "nvidia_vbios_vfio_patcher.py", line 103, in run_sanity_tests
"footer, found %d" % npde_count)
main.CheckException: Expected only three 'NPDE' markers between header and footer, found 2
```

**Comment by Matoking** [comment]
NVIDIA includes MX150 as a part of the Pascal series, but the vBIOS format it uses seems to differ from the rest of the series. If I had to guess, it would have something to do with the card not being a PCI-e card.

This script works by using the differences between full (what you'd get by dumping the BIOS with GPU-Z or a similar tool under Windows) and partial copies (what you'd get by dumping the ROM under Linux) of vBIOSes. Here's a [forum post](https://lime-technology.com/forums/topic/51230-video-guidehow-to-pass-through-an-nvidia-gpu-as-primary-or-only-gpu-in-unraid/?page=3&tab=comments#comment-580260) on Lime Technology forums I posted about this.

If I had a full and a partial copy of the same vBIOS, I might be able to do the same for this GPU, though at that point you wouldn't need this script in the first place. I also released this script since I was able to verify that it works with my own GTX 1070, so I wouldn't be able to make the same claim of compatibility with the MX150.

**Comment by T-vK** [comment]
I have the same issue with the "GTX 1060 Mobile with Max-Q Design".
Is there anything you or I can do?

Here's what I did:
```
## Download the vBIOS of the GTX 1060 Mobile with Max-Q Design
$ wget https://www.techpowerup.com/vgabios/205874/205874.rom
## Download the script
$ wget https://raw.githubusercontent.com/Matoking/NVIDIA-vBIOS-VFIO-Patcher/master/nvidia_vbios_vfio_patcher.py
## Make the script executable
$ chmod +x ./nvidia_vbios_vfio_patcher.py
## Run the script
$ ./nvidia_vbios_vfio_patcher.py -i 205874.rom -o 205874_patched.rom 
Opening the ROM file...
Scanning for ROM offsets...
Offsets found!
Running sanity checks...
Traceback (most recent call last):
  File "./nvidia_vbios_vfio_patcher.py", line 194, in <module>
    main()
  File "./nvidia_vbios_vfio_patcher.py", line 172, in main
    rom.run_sanity_tests(args.ignore_sanity_check)
  File "./nvidia_vbios_vfio_patcher.py", line 103, in run_sanity_tests
    "footer, found %d" % npde_count)
__main__.CheckException: Expected only three 'NPDE' markers between header and footer, found 2
```

I'm hoping to fix Nvidia's error 43 for mobile GPU-passthrough with this.

**Comment by T-vK** [comment]
New Laptop, this time with a normal GTX 1060 Mobile (without Max-Q design): Same problem.

**Comment by waltercool** [comment]
Same problem with GTX 1070 Max-Q

**Comment by bubbleguuum** [comment]
Same here with Quadro P600 (Pascal based).

**Comment by solarkraft** [comment]
I have a 1050 Ti Mobile and the same issue. Is there anything we can do about this?

**Comment by S-trace** [comment]
Same issue with 1050 TI Mobile.
I extracted Nvidia BIOS from UEFI BIOS for my laptop, here it is
[FX705GE-AS.307_NVidia_BIOS.bin.zip](https://github.com/Matoking/NVIDIA-vBIOS-VFIO-Patcher/files/7774739/FX705GE-AS.307_NVidia_BIOS.bin.zip)
.

**Comment by mjiang9999** [comment]
> 

please try to dump the rom on MSDOS, not windows
